language: android

jdk:
    - oraclejdk8

android:
    components:
        - tools
        - build-tools-23.0.3
        - android-24
        - extra-android-m2repository
        - extra-google-m2repository

before_install:
    - echo "sdk.dir=$ANDROID_HOME" > local.properties

script:
    - ./gradlew clean test

notifications:
    email: false

sudo: false

cache:
    directories:
        - $HOME/.gradle
